### ISSUE TITLE
Shop - Collection Page

### ISSUE THREAD

**Issue by devinschumacher** [serpcompany/__collaborators-va#3]
- instructions: https://www.loom.com/share/87149d2b7ea64841b357d440a55fadff

reference pages: 
- https://reverb.com/brand/audio-technica?product_type=dj-and-lighting-gear&category=turntables
- https://staging.serp.co/shop/best/couples-pajamas/ (login: `admin`; password: `pw`)

---

- [ ] HTML template
- [ ] storybook

**Comment by codescandy** [comment]
@devinschumacher As given feedback page is also improved. 

https://serp-components.netlify.app/?path=/story/templates-shop--shop-collection-layout
Let me know. If need to edit some.

Thank you.
